### ISSUE TITLE
Will this project see the light of day?

### ISSUE THREAD

**Issue by mykeels** [Olamyy/nairalandnlptoolkit#1]
Hey, I was showing a friend your work on NLP, and decided to troll this repo. Great stuff! Apologies if it's not funny.

**Comment by Olamyy** [comment]
Hey,

Yeah. The project will depend on these. 
1. https://github.com/Olamyy/nairaland . This is a crawler.. 
2. https://github.com/Olamyy/nairaland_api . This is (supposed to be) a rest API on the data from 1 above.

2's not really important but 1 is. The crawler is still running and has about 1.5M topics( with comments, user details). 
Once I feel I have enough, I'll get back to this.

In the meantime, there's a team in AISaturdays Lagos that's using the data from the crawler to build a conversational system. I don't have much information about it yet but i can link you up with the team if you're interested in following up with it.
